# Generated by Django 2.2.5 on 2020-09-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
