# Generated by Django 2.2.5 on 2020-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200922_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='remaining_tickets',
            field=models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField(blank=True, null=True), null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='num_tickets',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
