# Generated by Django 2.2.5 on 2020-09-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200923_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='event_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
